### ISSUE TITLE
Lỗi Logout

### ISSUE THREAD

**Issue by luongtuanlinh** [hoangHEDSPI/socket_programming#1]
Khi đăng xuất, nhập đúng password nhưng vẫn báo sai password => không thể logout

![laptrinhmang1](https://user-images.githubusercontent.com/28508418/51232849-be4ebd00-199a-11e9-8212-3a2e91441a5e.png)

**Comment by PhVHoang** [comment]
> Khi đăng xuất, nhập đúng password nhưng vẫn báo sai password => không thể logout
> 
> ![laptrinhmang1](https://user-images.githubusercontent.com/28508418/51232849-be4ebd00-199a-11e9-8212-3a2e91441a5e.png)

 A fix rồi e thử lại xem nhé.
